name: 'github-test-action'
description: 'Testing created github action'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, Naveen!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Naveen Add other actions to build,
          echo test, Naveen and deploy your project.