name: 'github-test-action'
description: 'Testing created github action'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Navin'

runs:
  using: "composite"
  steps: 
    - run: echo welcome MR ${{ inputs.who-to-greet }}.
      shell: bash

